
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hyd
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  security:
    user:
      name: admin
      password: Nikhil

  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql=true:


